---
# tasks file for vim-ansible-role
- name: VIM | Make directories for vim-pathogen
  file: 
    path: "{{ ansible_env.HOME }}/.vim/{{ item }}"
    state: directory
  with_items:
    - autoload
    - bundle
    - syntax

- name: VIM | install pathogen.vim
  get_url:
    url: "https://tpo.pe/pathogen.vim"
    dest: "{{ ansible_env.HOME }}/.vim/autoload"
    force: no

- name: VIM | install vim syntax highliters
  get_url:
    url: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.vim/syntax"
    force: no
  with_items: "{{ VIM_SYNTAX_PLUGINS }}"

- name: VIM | install vim plugins
  git:
    url: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.vim/bundle"
    force: true
    update: no
  with_items: "{{ VIM_PLUGINS }}"

- name: VIM | deploy vim configuration file
  template:
    src: vimrc.j2
    dest: "{{ ansible_env.HOME }}/.vimrc"
